export const ADD_CHOSEN_INGREDIENT: 'ADD_CHOSEN_INGREDIENT' =
  'ADD_CHOSEN_INGREDIENT'
export const DELETE_CHOSEN_INGREDIENT: 'DELETE_CHOSEN_INGREDIENT' =
  'DELETE_CHOSEN_INGREDIENT'
export const SORT_CHOSEN_INGREDIENTS: 'SORT_CHOSEN_INGREDIENTS' =
  'SORT_CHOSEN_INGREDIENTS'
export const CLEAR_CHOSEN_INGREDIENTS: 'CLEAN_CHOSEN_INGREDIENTS' =
  'CLEAN_CHOSEN_INGREDIENTS'
