export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' =
  'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' =
  'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_ERROR' =
  'GET_INGREDIENTS_ERROR'

export const INCREASE_INGREDIENT_VALUE: 'INCREASE_INGREDIENT_VALUE' =
  'INCREASE_INGREDIENT_VALUE'
export const DECREASE_INGREDIENT_VALUE: 'DECREASE_INGREDIENT_VALUE' =
  'DECREASE_INGREDIENT_VALUE'
