export const SEND_ORDER_REQUEST: 'SEND_ORDER_REQUEST' = 'SEND_ORDER_REQUEST'
export const SEND_ORDER_SUCCESS: 'SEND_ORDER_SUCCESS' = 'SEND_ORDER_SUCCESS'
export const SEND_ORDER_ERROR: 'SEND_ORDER_ERROR' = 'SEND_ORDER_ERROR'

export const SHOW_ORDER_MODAL: 'SHOW_ORDER_MODAL' = 'SHOW_ORDER_MODAL'
export const HIDE_ORDER_MODAL: 'HIDE_ORDER_MODAL' = 'HIDE_ORDER_MODAL'
